package com.example.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.greendao.Note;
import com.example.greendao.Model1;

import com.example.greendao.NoteDao;
import com.example.greendao.Model1Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;
    private final DaoConfig model1DaoConfig;

    private final NoteDao noteDao;
    private final Model1Dao model1Dao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        model1DaoConfig = daoConfigMap.get(Model1Dao.class).clone();
        model1DaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(noteDaoConfig, this);
        model1Dao = new Model1Dao(model1DaoConfig, this);

        registerDao(Note.class, noteDao);
        registerDao(Model1.class, model1Dao);
    }
    
    public void clear() {
        noteDaoConfig.getIdentityScope().clear();
        model1DaoConfig.getIdentityScope().clear();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public Model1Dao getModel1Dao() {
        return model1Dao;
    }

}
