package com.example.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MODEL1".
 */
public class Model1 {

    private Long id;
    /** Not-null value. */
    private String name;
    private int ints;

    public Model1() {
    }

    public Model1(Long id) {
        this.id = id;
    }

    public Model1(Long id, String name, int ints) {
        this.id = id;
        this.name = name;
        this.ints = ints;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public int getInts() {
        return ints;
    }

    public void setInts(int ints) {
        this.ints = ints;
    }

    @Override
    public String toString() {
        return "Model1{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", ints=" + ints +
                '}';
    }
}
